global:
  scrape_interval: 15s

scrape_configs:
#  - job_name: 'otel-collector'
#    static_configs:
#      - targets: ['otel-collector:8888']

  - job_name: 'otel-collector-2'
    static_configs:
      - targets: ['otel-collector:8889']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
